//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ZhrReadPayrollResult.RfcException", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZhrReadPayrollResultRfcException
    {
        
        private ZhrReadPayrollResultRfcExceptions nameField;
        
        private string textField;
        
        private RfcExceptionMessage messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZhrReadPayrollResultRfcExceptions Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RfcExceptionMessage Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ZhrReadPayrollResult.RfcExceptions", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public enum ZhrReadPayrollResultRfcExceptions
    {
        
        /// <remarks/>
        NoPayrollResult,
        
        /// <remarks/>
        NoPeriodFound,
        
        /// <remarks/>
        NoPernrFound,
        
        /// <remarks/>
        PeriodEmpty,
        
        /// <remarks/>
        PernrEmpty,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RfcException.Message", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcExceptionMessage
    {
        
        private string idField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr005SYasalKesintiler
    {
        
        private decimal sigortagunuField;
        
        private decimal sigortamatrahiField;
        
        private decimal gelirvergisimatrahiField;
        
        private decimal sakatlikindField;
        
        private decimal digerindField;
        
        private decimal vergiyetabimatrahField;
        
        private decimal kumulatifmatrahField;
        
        private decimal kumulatifvergiField;
        
        private decimal damgavergisimatrahiField;
        
        private decimal sskiscipayiField;
        
        private decimal issizlikiscipayiField;
        
        private decimal gelirvergisiField;
        
        private decimal damgavergisiField;
        
        private decimal isverensskpayiField;
        
        private decimal yasalkesintilertoplamiField;
        
        private decimal issizlikisverenpayiField;
        
        private decimal _34857kanuntesvikiField;
        
        private string ucretpbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Sigortagunu
        {
            get
            {
                return this.sigortagunuField;
            }
            set
            {
                this.sigortagunuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Sigortamatrahi
        {
            get
            {
                return this.sigortamatrahiField;
            }
            set
            {
                this.sigortamatrahiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Gelirvergisimatrahi
        {
            get
            {
                return this.gelirvergisimatrahiField;
            }
            set
            {
                this.gelirvergisimatrahiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Sakatlikind
        {
            get
            {
                return this.sakatlikindField;
            }
            set
            {
                this.sakatlikindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Digerind
        {
            get
            {
                return this.digerindField;
            }
            set
            {
                this.digerindField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Vergiyetabimatrah
        {
            get
            {
                return this.vergiyetabimatrahField;
            }
            set
            {
                this.vergiyetabimatrahField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Kumulatifmatrah
        {
            get
            {
                return this.kumulatifmatrahField;
            }
            set
            {
                this.kumulatifmatrahField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Kumulatifvergi
        {
            get
            {
                return this.kumulatifvergiField;
            }
            set
            {
                this.kumulatifvergiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Damgavergisimatrahi
        {
            get
            {
                return this.damgavergisimatrahiField;
            }
            set
            {
                this.damgavergisimatrahiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Sskiscipayi
        {
            get
            {
                return this.sskiscipayiField;
            }
            set
            {
                this.sskiscipayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Issizlikiscipayi
        {
            get
            {
                return this.issizlikiscipayiField;
            }
            set
            {
                this.issizlikiscipayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Gelirvergisi
        {
            get
            {
                return this.gelirvergisiField;
            }
            set
            {
                this.gelirvergisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Damgavergisi
        {
            get
            {
                return this.damgavergisiField;
            }
            set
            {
                this.damgavergisiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal Isverensskpayi
        {
            get
            {
                return this.isverensskpayiField;
            }
            set
            {
                this.isverensskpayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal Yasalkesintilertoplami
        {
            get
            {
                return this.yasalkesintilertoplamiField;
            }
            set
            {
                this.yasalkesintilertoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal Issizlikisverenpayi
        {
            get
            {
                return this.issizlikisverenpayiField;
            }
            set
            {
                this.issizlikisverenpayiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_--34857kanuntesviki", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal _34857kanuntesviki
        {
            get
            {
                return this._34857kanuntesvikiField;
            }
            set
            {
                this._34857kanuntesvikiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Ucretpb
        {
            get
            {
                return this.ucretpbField;
            }
            set
            {
                this.ucretpbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr005SPersonelBilgi
    {
        
        private string sirketkoduField;
        
        private string firmaField;
        
        private string departmanField;
        
        private string sirketsicilnoField;
        
        private string adsoyadField;
        
        private string personelnoField;
        
        private string tckimliknoField;
        
        private string sigortanoField;
        
        private string isegirisField;
        
        private string sskstatuField;
        
        private string donemField;
        
        private string gorevField;
        
        private string hesapnoField;
        
        private string ucretcinsiField;
        
        private decimal ucrettutariField;
        
        private string ucretpbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Sirketkodu
        {
            get
            {
                return this.sirketkoduField;
            }
            set
            {
                this.sirketkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Departman
        {
            get
            {
                return this.departmanField;
            }
            set
            {
                this.departmanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Sirketsicilno
        {
            get
            {
                return this.sirketsicilnoField;
            }
            set
            {
                this.sirketsicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Adsoyad
        {
            get
            {
                return this.adsoyadField;
            }
            set
            {
                this.adsoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Personelno
        {
            get
            {
                return this.personelnoField;
            }
            set
            {
                this.personelnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Tckimlikno
        {
            get
            {
                return this.tckimliknoField;
            }
            set
            {
                this.tckimliknoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Sigortano
        {
            get
            {
                return this.sigortanoField;
            }
            set
            {
                this.sigortanoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Isegiris
        {
            get
            {
                return this.isegirisField;
            }
            set
            {
                this.isegirisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Sskstatu
        {
            get
            {
                return this.sskstatuField;
            }
            set
            {
                this.sskstatuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Donem
        {
            get
            {
                return this.donemField;
            }
            set
            {
                this.donemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Gorev
        {
            get
            {
                return this.gorevField;
            }
            set
            {
                this.gorevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Hesapno
        {
            get
            {
                return this.hesapnoField;
            }
            set
            {
                this.hesapnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Ucretcinsi
        {
            get
            {
                return this.ucretcinsiField;
            }
            set
            {
                this.ucretcinsiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal Ucrettutari
        {
            get
            {
                return this.ucrettutariField;
            }
            set
            {
                this.ucrettutariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string Ucretpb
        {
            get
            {
                return this.ucretpbField;
            }
            set
            {
                this.ucretpbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr005SOzelKesintiler
    {
        
        private decimal yillikizinField;
        
        private decimal trafikhgscezaField;
        
        private decimal telefondataField;
        
        private decimal ozelsigortaField;
        
        private decimal netprimField;
        
        private decimal avansField;
        
        private decimal besField;
        
        private decimal ozelkesintilertoplamiField;
        
        private string ucretpbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Yillikizin
        {
            get
            {
                return this.yillikizinField;
            }
            set
            {
                this.yillikizinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Trafikhgsceza
        {
            get
            {
                return this.trafikhgscezaField;
            }
            set
            {
                this.trafikhgscezaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Telefondata
        {
            get
            {
                return this.telefondataField;
            }
            set
            {
                this.telefondataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Ozelsigorta
        {
            get
            {
                return this.ozelsigortaField;
            }
            set
            {
                this.ozelsigortaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Netprim
        {
            get
            {
                return this.netprimField;
            }
            set
            {
                this.netprimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Avans
        {
            get
            {
                return this.avansField;
            }
            set
            {
                this.avansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Bes
        {
            get
            {
                return this.besField;
            }
            set
            {
                this.besField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Ozelkesintilertoplami
        {
            get
            {
                return this.ozelkesintilertoplamiField;
            }
            set
            {
                this.ozelkesintilertoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Ucretpb
        {
            get
            {
                return this.ucretpbField;
            }
            set
            {
                this.ucretpbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr005SKazanclar
    {
        
        private decimal normalcalismagunField;
        
        private decimal normalcalismasaatField;
        
        private decimal normalcalismatutarField;
        
        private decimal haftatatiligunField;
        
        private decimal haftatatilisaatField;
        
        private decimal haftatatilitutarField;
        
        private decimal resmitatilgunField;
        
        private decimal resmitatilsaatField;
        
        private decimal resmitatiltutarField;
        
        private decimal fm50saatField;
        
        private decimal fm50tutarField;
        
        private decimal fm100saatField;
        
        private decimal fm100tutarField;
        
        private decimal fmtoplamisaatField;
        
        private decimal fmtoplamitutarField;
        
        private decimal tumkazanclartoplamiField;
        
        private decimal tumkesintilertoplamiField;
        
        private decimal asgarigecimindirimiField;
        
        private decimal netodenentoplamiField;
        
        private string ucretpbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Normalcalismagun
        {
            get
            {
                return this.normalcalismagunField;
            }
            set
            {
                this.normalcalismagunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Normalcalismasaat
        {
            get
            {
                return this.normalcalismasaatField;
            }
            set
            {
                this.normalcalismasaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Normalcalismatutar
        {
            get
            {
                return this.normalcalismatutarField;
            }
            set
            {
                this.normalcalismatutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Haftatatiligun
        {
            get
            {
                return this.haftatatiligunField;
            }
            set
            {
                this.haftatatiligunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Haftatatilisaat
        {
            get
            {
                return this.haftatatilisaatField;
            }
            set
            {
                this.haftatatilisaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Haftatatilitutar
        {
            get
            {
                return this.haftatatilitutarField;
            }
            set
            {
                this.haftatatilitutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Resmitatilgun
        {
            get
            {
                return this.resmitatilgunField;
            }
            set
            {
                this.resmitatilgunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Resmitatilsaat
        {
            get
            {
                return this.resmitatilsaatField;
            }
            set
            {
                this.resmitatilsaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Resmitatiltutar
        {
            get
            {
                return this.resmitatiltutarField;
            }
            set
            {
                this.resmitatiltutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Fm50saat
        {
            get
            {
                return this.fm50saatField;
            }
            set
            {
                this.fm50saatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Fm50tutar
        {
            get
            {
                return this.fm50tutarField;
            }
            set
            {
                this.fm50tutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Fm100saat
        {
            get
            {
                return this.fm100saatField;
            }
            set
            {
                this.fm100saatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Fm100tutar
        {
            get
            {
                return this.fm100tutarField;
            }
            set
            {
                this.fm100tutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal Fmtoplamisaat
        {
            get
            {
                return this.fmtoplamisaatField;
            }
            set
            {
                this.fmtoplamisaatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal Fmtoplamitutar
        {
            get
            {
                return this.fmtoplamitutarField;
            }
            set
            {
                this.fmtoplamitutarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal Tumkazanclartoplami
        {
            get
            {
                return this.tumkazanclartoplamiField;
            }
            set
            {
                this.tumkazanclartoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal Tumkesintilertoplami
        {
            get
            {
                return this.tumkesintilertoplamiField;
            }
            set
            {
                this.tumkesintilertoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal Asgarigecimindirimi
        {
            get
            {
                return this.asgarigecimindirimiField;
            }
            set
            {
                this.asgarigecimindirimiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal Netodenentoplami
        {
            get
            {
                return this.netodenentoplamiField;
            }
            set
            {
                this.netodenentoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Ucretpb
        {
            get
            {
                return this.ucretpbField;
            }
            set
            {
                this.ucretpbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zhr005SEkodemeler
    {
        
        private decimal yolparasibrutField;
        
        private decimal netevlilikField;
        
        private decimal nbevlilikField;
        
        private decimal nkevlilikField;
        
        private decimal netdogumField;
        
        private decimal nbdogumField;
        
        private decimal nkdogumField;
        
        private decimal cocukField;
        
        private decimal kidemField;
        
        private decimal ihbarField;
        
        private decimal primField;
        
        private decimal avansField;
        
        private decimal netolumField;
        
        private decimal nbolumField;
        
        private decimal nkolumField;
        
        private decimal nettahsilField;
        
        private decimal nbtahsilField;
        
        private decimal nktahsilField;
        
        private decimal netyemekField;
        
        private decimal nbyemekField;
        
        private decimal nkyemekField;
        
        private decimal ekodemelertoplamiField;
        
        private string ucretpbField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal Yolparasibrut
        {
            get
            {
                return this.yolparasibrutField;
            }
            set
            {
                this.yolparasibrutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal Netevlilik
        {
            get
            {
                return this.netevlilikField;
            }
            set
            {
                this.netevlilikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal Nbevlilik
        {
            get
            {
                return this.nbevlilikField;
            }
            set
            {
                this.nbevlilikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Nkevlilik
        {
            get
            {
                return this.nkevlilikField;
            }
            set
            {
                this.nkevlilikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Netdogum
        {
            get
            {
                return this.netdogumField;
            }
            set
            {
                this.netdogumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal Nbdogum
        {
            get
            {
                return this.nbdogumField;
            }
            set
            {
                this.nbdogumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Nkdogum
        {
            get
            {
                return this.nkdogumField;
            }
            set
            {
                this.nkdogumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal Cocuk
        {
            get
            {
                return this.cocukField;
            }
            set
            {
                this.cocukField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal Kidem
        {
            get
            {
                return this.kidemField;
            }
            set
            {
                this.kidemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal Ihbar
        {
            get
            {
                return this.ihbarField;
            }
            set
            {
                this.ihbarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal Prim
        {
            get
            {
                return this.primField;
            }
            set
            {
                this.primField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal Avans
        {
            get
            {
                return this.avansField;
            }
            set
            {
                this.avansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal Netolum
        {
            get
            {
                return this.netolumField;
            }
            set
            {
                this.netolumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public decimal Nbolum
        {
            get
            {
                return this.nbolumField;
            }
            set
            {
                this.nbolumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal Nkolum
        {
            get
            {
                return this.nkolumField;
            }
            set
            {
                this.nkolumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal Nettahsil
        {
            get
            {
                return this.nettahsilField;
            }
            set
            {
                this.nettahsilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal Nbtahsil
        {
            get
            {
                return this.nbtahsilField;
            }
            set
            {
                this.nbtahsilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal Nktahsil
        {
            get
            {
                return this.nktahsilField;
            }
            set
            {
                this.nktahsilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal Netyemek
        {
            get
            {
                return this.netyemekField;
            }
            set
            {
                this.netyemekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal Nbyemek
        {
            get
            {
                return this.nbyemekField;
            }
            set
            {
                this.nbyemekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal Nkyemek
        {
            get
            {
                return this.nkyemekField;
            }
            set
            {
                this.nkyemekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal Ekodemelertoplami
        {
            get
            {
                return this.ekodemelertoplamiField;
            }
            set
            {
                this.ekodemelertoplamiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string Ucretpb
        {
            get
            {
                return this.ucretpbField;
            }
            set
            {
                this.ucretpbField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF")]
    public interface ZHR_READ_PAYROLL_RESULT_SDEF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:soap:functions:mc-style:ZHR_READ_PAYROLL_RESULT_SDEF:Zhr" +
            "ReadPayrollResultRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(PayrollService.ZhrReadPayrollResultRfcException), Action="urn:sap-com:document:sap:soap:functions:mc-style:ZHR_READ_PAYROLL_RESULT_SDEF:Zhr" +
            "ReadPayrollResultRequest", Name="ZhrReadPayrollResult.Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<PayrollService.ZhrReadPayrollResultResponse1> ZhrReadPayrollResultAsync(PayrollService.ZhrReadPayrollResultRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZhrReadPayrollResult
    {
        
        private string iPeriodField;
        
        private string iPernrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IPeriod
        {
            get
            {
                return this.iPeriodField;
            }
            set
            {
                this.iPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IPernr
        {
            get
            {
                return this.iPernrField;
            }
            set
            {
                this.iPernrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZhrReadPayrollResultResponse
    {
        
        private Zhr005SEkodemeler esEkodemelerField;
        
        private Zhr005SKazanclar esKazanclarField;
        
        private Zhr005SOzelKesintiler esOzelKesintilerField;
        
        private Zhr005SPersonelBilgi esPersonelBilgiField;
        
        private Zhr005SYasalKesintiler esYasalKesintilerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Zhr005SEkodemeler EsEkodemeler
        {
            get
            {
                return this.esEkodemelerField;
            }
            set
            {
                this.esEkodemelerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Zhr005SKazanclar EsKazanclar
        {
            get
            {
                return this.esKazanclarField;
            }
            set
            {
                this.esKazanclarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Zhr005SOzelKesintiler EsOzelKesintiler
        {
            get
            {
                return this.esOzelKesintilerField;
            }
            set
            {
                this.esOzelKesintilerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Zhr005SPersonelBilgi EsPersonelBilgi
        {
            get
            {
                return this.esPersonelBilgiField;
            }
            set
            {
                this.esPersonelBilgiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Zhr005SYasalKesintiler EsYasalKesintiler
        {
            get
            {
                return this.esYasalKesintilerField;
            }
            set
            {
                this.esYasalKesintilerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZhrReadPayrollResultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PayrollService.ZhrReadPayrollResult ZhrReadPayrollResult;
        
        public ZhrReadPayrollResultRequest()
        {
        }
        
        public ZhrReadPayrollResultRequest(PayrollService.ZhrReadPayrollResult ZhrReadPayrollResult)
        {
            this.ZhrReadPayrollResult = ZhrReadPayrollResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZhrReadPayrollResultResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public PayrollService.ZhrReadPayrollResultResponse ZhrReadPayrollResultResponse;
        
        public ZhrReadPayrollResultResponse1()
        {
        }
        
        public ZhrReadPayrollResultResponse1(PayrollService.ZhrReadPayrollResultResponse ZhrReadPayrollResultResponse)
        {
            this.ZhrReadPayrollResultResponse = ZhrReadPayrollResultResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ZHR_READ_PAYROLL_RESULT_SDEFChannel : PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ZHR_READ_PAYROLL_RESULT_SDEFClient : System.ServiceModel.ClientBase<PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF>, PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF
    {
        
        public ZHR_READ_PAYROLL_RESULT_SDEFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PayrollService.ZhrReadPayrollResultResponse1> PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF.ZhrReadPayrollResultAsync(PayrollService.ZhrReadPayrollResultRequest request)
        {
            return base.Channel.ZhrReadPayrollResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<PayrollService.ZhrReadPayrollResultResponse1> ZhrReadPayrollResultAsync(PayrollService.ZhrReadPayrollResult ZhrReadPayrollResult)
        {
            PayrollService.ZhrReadPayrollResultRequest inValue = new PayrollService.ZhrReadPayrollResultRequest();
            inValue.ZhrReadPayrollResult = ZhrReadPayrollResult;
            return ((PayrollService.ZHR_READ_PAYROLL_RESULT_SDEF)(this)).ZhrReadPayrollResultAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
